variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build

build_mac_x64:
  environment:
    name: vincss
  stage: build
  script:
    - pip install requests boto3
    - python3 deploy.py
  tags:
    - mac-intel
  only:
    - mac-vincss
    - tags

