variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build

build_windows_x64:
  stage: build
  script:
    - pip install requests boto3
    - python deploy.py
  tags:
    - win01
  only:
    - dev
    - tags

build_linux_x64:
  stage: build
  script:
    - pip install requests boto3
    - python3 deploy.py
  tags:
    - cs_newgen
  only:
    - dev
    - tags

build_mac_x64:
  stage: build
  script:
    - pip install requests boto3
    - python3 deploy.py
  tags:
    - mac-intel
  only:
    - dev
    - tags