variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build

build_mac_x64:
  stage: build
  script:
    - pip install requests boto3
    - python deploy.py
  tags:
    - mac-intel
  only:
    - duchm-vincss
    - tags

